dist: trusty
sudo: true
  #
language: c
  #
notifications:
  email: false
  #
before_install:
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}
  #
  # Start fb X server
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  #
install:
  #
  # Install arduino 1.8.9
  - wget https://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz
  - tar xf arduino-1.8.9-linux64.tar.xz
  - sudo mv arduino-1.8.9 /usr/local/share/arduino
  - ln -s /usr/local/share/arduino/arduino ${TRAVIS_BUILD_DIR}/buildroot/bin/arduino
  #
  # Install: LiquidCrystal_I2C library
  - git clone https://github.com/kiyoshigawa/LiquidCrystal_I2C.git
  - mv LiquidCrystal_I2C/LiquidCrystal_I2C /usr/local/share/arduino/libraries/LiquidCrystal_I2C
  #
  # Install: LiquidTWI2 library
  - git clone https://github.com/lincomatic/LiquidTWI2.git
  - sudo mv LiquidTWI2 /usr/local/share/arduino/libraries/LiquidTWI2
  #
  # Install: Monochrome Graphics Library for LCDs and OLEDs
  - git clone https://github.com/olikraus/U8glib_Arduino.git
  - sudo mv U8glib_Arduino /usr/local/share/arduino/libraries/U8glib
  #
before_script:
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  #
  # Generate custom version include
  - generate_version_header_for_marlin ${TRAVIS_BUILD_DIR}/Marlin
  - cat ${TRAVIS_BUILD_DIR}/Marlin/_Version.h
  #
script:
  #
  # Backup Configuration.h, Configuration_adv.h, and pins_RAMPS.h
  #
  - cp Marlin/Configuration.h Marlin/Configuration.h.backup
  - cp Marlin/Configuration_adv.h Marlin/Configuration_adv.h.backup
  - cp Marlin/pins_RAMPS.h Marlin/pins_RAMPS.h.backup
  #
  # Build with the default configurations
  #
  - build_marlin
